# Pre-commit configuration for MongoDB Atlas Slack Bot
# This file configures automatic code quality checks before git commits

repos:
  # Local hooks that use our Makefile
  - repo: local
    hooks:
      - id: python-format
        name: Format Python code
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: python-lint
        name: Lint Python code
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: python-test
        name: Run Python tests
        entry: make test
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: python-security
        name: Security checks
        entry: make security
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: python-syntax
        name: Syntax check
        entry: make syntax-check
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with newline
      - id: check-yaml
        name: Check YAML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
  
# Configuration
default_language_version:
  python: python3.10

# Skip certain files
exclude: |
  (?x)^(
      \.git/|
      \.mypy_cache/|
      __pycache__/|
      \.pytest_cache/|
      \.venv/|
      venv/|
      env/|
      node_modules/|
      security-report\.json|
      temp_test\.py|
      output\.json|
      \.python-version|
      \.flake8|
      \.pylintrc|
      \.pre-commit-config\.yaml|
      Makefile|
      requirements.*\.txt|
      setup-env\.sh|
      setup\.py|
      \.md$
  )$ 